# ref: https://github.com/docker-library/official-images
name: amd64 Docker

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check docker
        run: |
          docker version
          docker info
          docker buildx ls
      - name: Build env image
        run: docker build --target env .
      - name: Build devel image
        run: docker build --target devel .
      - name: Build project
        run: docker build --target build .
      - name: Run project
        run: docker build --target run --progress plain .
      - name: Pack project
        run: docker build --target pack .
