# ref: https://github.com/actions/runner-images
name: amd64 MacOS

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    name: MacOS • Java
    runs-on: macos-latest # arm64 based macos runner
    steps:
    - uses: actions/checkout@v4
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn exec:java
    - name: Package
      run: mvn package
