name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
    - name: docker build env
      run: docker build --target env .
    - name: docker build devel
      run: docker build --target devel .
    - name: docker build build
      run: docker build --target build .
    - name: docker build test
      run: docker build --target test .

